# Generated by Django 4.1.3 on 2022-11-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipos_medicos',
            fields=[
                ('id_equipo', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_serie', models.IntegerField()),
                ('tipo_equipo', models.TextField(choices=[('Elige el tipo de equipo', 'Elige el tipo de equipo'), ('Ventilador', 'Ventilador'), ('Incubadora', 'Incubadora'), ('Bomba de infusión', 'Bomba de Infusión'), ('Capnógrafo', 'Capnógrafo'), ('EEG', 'EEG'), ('EKG', 'EKG'), ('Saturómetro', 'Saturómetro'), ('Bomba de jeringas', 'Bomba de jeringas')], default='Elige el tipo de equipo', max_length=70)),
                ('descripcion', models.TextField(max_length=250)),
                ('marca', models.TextField(max_length=50)),
                ('condicion', models.TextField(choices=[('Buen estado', 'Buen estado'), ('Requiere mantenimiento', 'Requiere mantenimiento'), ('No utilizable', 'No utilizable')], default='Buen estado', max_length=50)),
                ('estado', models.TextField(choices=[('Disponible', 'Disponible'), ('En cupo', 'En cupo'), ('En mantenimiento', 'En mantenimiento'), ('En préstamo', 'En préstamo')], default='Disponible', max_length=50)),
                ('fecha_mantencion', models.DateField()),
            ],
        ),
    ]
