# Generated by Django 4.1.3 on 2022-11-23 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cupo',
            fields=[
                ('id_cupo', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='equipo_medico',
            fields=[
                ('id_equipo', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_serie', models.IntegerField()),
                ('tipo_equipo', models.TextField(choices=[('Elige el tipo de equipo', 'Elige el tipo de equipo'), ('Ventilador', 'Ventilador'), ('Incubadora', 'Incubadora'), ('Bomba de infusión', 'Bomba de Infusión'), ('Capnógrafo', 'Capnógrafo'), ('EEG', 'EEG'), ('EKG', 'EKG'), ('Saturómetro', 'Saturómetro'), ('Bomba de jeringas', 'Bomba de jeringas')], default='Elige el tipo de equipo', max_length=70)),
                ('descripcion', models.TextField(max_length=250)),
                ('marca', models.TextField(max_length=50)),
                ('condicion', models.TextField(choices=[('Buen estado', 'Buen estado'), ('Requiere mantenimiento', 'Requiere mantenimiento'), ('No utilizable', 'No utilizable')], default='Buen estado', max_length=50)),
                ('estado', models.TextField(choices=[('Disponible', 'Disponible'), ('En cupo', 'En cupo'), ('En mantenimiento', 'En mantenimiento'), ('En préstamo', 'En préstamo')], default='Disponible', max_length=50)),
                ('fecha_mantencion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='matrona',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('id_superior', models.IntegerField()),
                ('nombre', models.TextField(max_length=50)),
                ('paterno', models.TextField(max_length=50)),
                ('materno', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id_prestamo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('hospital_destino', models.TextField(max_length=100)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipo_medico')),
            ],
        ),
        migrations.CreateModel(
            name='traslado',
            fields=[
                ('id_traslado', models.IntegerField(primary_key=True, serialize=False)),
                ('destino', models.TextField(max_length=150)),
                ('fecha_traslado', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipo_medico')),
            ],
        ),
        migrations.DeleteModel(
            name='equipos_medicos',
        ),
        migrations.CreateModel(
            name='matrona_clinica',
            fields=[
                ('matrona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.matrona')),
            ],
            bases=('core.matrona',),
        ),
        migrations.CreateModel(
            name='matrona_coordinadora',
            fields=[
                ('matrona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.matrona')),
            ],
            bases=('core.matrona',),
        ),
        migrations.AddField(
            model_name='traslado',
            name='id_matrona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matrona_clinica'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_matrona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matrona_clinica'),
        ),
        migrations.AddField(
            model_name='equipo_medico',
            name='id_matrona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matrona_coordinadora'),
        ),
        migrations.CreateModel(
            name='equipo_en_cupo',
            fields=[
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.equipo_medico')),
                ('id_cupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cupo')),
                ('id_matrona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matrona_clinica')),
            ],
        ),
    ]
