# Generated by Django 4.1.3 on 2022-11-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cupo_equipo_medico_matrona_prestamo_traslado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrona',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='matrona',
            name='password',
            field=models.TextField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='matrona',
            name='username',
            field=models.TextField(max_length=100, null=True, unique=True, verbose_name='Nombre de usuario'),
        ),
        migrations.AddField(
            model_name='matrona',
            name='usuario_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matrona',
            name='usuario_administrador',
            field=models.BooleanField(default=False),
        ),
    ]
