# Generated by Django 4.1.3 on 2022-11-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_matrona_last_login_matrona_password_matrona_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrona',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='matrona',
            name='password',
        ),
        migrations.RemoveField(
            model_name='matrona',
            name='usuario_activo',
        ),
        migrations.RemoveField(
            model_name='matrona',
            name='usuario_administrador',
        ),
        migrations.RemoveField(
            model_name='traslado',
            name='destino',
        ),
        migrations.AlterField(
            model_name='matrona',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
