# Generated by Django 4.1.3 on 2022-11-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_matrona_last_login_remove_matrona_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traslado',
            name='razon',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
