# Generated by Django 4.1.3 on 2022-11-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_traslado_razon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrona',
            name='id_superior',
            field=models.IntegerField(null=True),
        ),
    ]
