# Generated by Django 4.1.3 on 2022-11-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_matrona_id_superior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrona',
            name='id_superior',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
