# Generated by Django 4.1.3 on 2022-11-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_matrona_id_superior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrona',
            name='materno',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='traslado',
            name='razon',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
